// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bffladnqomjaxcbcxwcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZmxhZG5xb21qYXhjYmN4d2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNzUyMjMsImV4cCI6MjA1Nzg1MTIyM30.-67Whzy4OguykmluCrTMZ_EnGPP_aN4O4pO0sGbDfe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);